Remove usages of Guice
jenkinsci/pipeline-input-step-plugin pull request #64
Opened 2021-12-24 18:08 UTC by basil

Replacing deprecated usages of Guice with non-deprecated non-Guice equivalents.

2021-12-24 20:04 UTC, basil commented
[BOM testing passed](https://ci.jenkins.io/job/Tools/job/bom/job/PR-783/1/)

2021-12-24 20:09 UTC, timja approved these changes

2022-01-03 23:01 UTC, jglick requested changes

2022-01-03 23:01 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
> +            return run.getParent().hasPermission(Job.BUILD);
https://github.com/jenkinsci/acceptance-test-harness/issues/727

2022-01-03 23:04 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
> +public class InputStep extends Step implements Serializable {
Also not compatible in this case.

2022-01-03 23:08 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
> +public class InputStep extends Step implements Serializable {
(Part of `program.dat`. Also see https://github.com/jenkinsci/pipeline-plugin/commit/7a0f10c21ddc40dc20f62d1b9d27633a7bf8aed4)

2022-01-04 15:48 UTC, basil commented
Closing in favor of #69.

2022-01-04 15:48 UTC, closed without merging